export interface IHotThreadItemRespond {
  itemid: string,
  id: string,
  idtype: string,
  title: string,
  url: string,
  pic: string,
  displayorder: number,
  coverpath: string,
  content: string,
  hasAuth: boolean,
  fields: {
    fulltitle: string,
    threads: string,
    author: string,
    authorid: string,
    avatar: string,
    avatar_middle: string,
    avatar_big: string,
    posts: string,
    todayposts: string,
    lastpost: string,
    lastposter: string,
    dateline: string,
    replies: string,
    forumurl: string,
    forumname: string,
    typename: string,
    typeicon: string,
    typeurl: string,
    sortname: string,
    sorturl: string,
    views: string,
    heats: string,
    recommends: string,
    hourviews: string,
    todayviews: string,
    weekviews: string,
    monthviews: string
  }
}

export interface IThreadRespond {
  floors: {
    pid: string,
    fid: string,
    tid: string,
    author: string,
    authorid: string,
    subject: string,
    dateline: string,
    message: string,
    avatar: string,
    uid: string,
    position: string,
    views: number,
    groupid: string,
    number: string,
    dbdateline: string,
    authortitle: string,
    ratelog?: {},
    ratelogextcredits?: {
      '1'?: number,
      '3'?: number,
      '4'?: number
    },
    totalrate: string[]
  }[],
  thread: {
    tid: string,
    fid: string,
    author: string,
    authorid: string,
    subject: string,
    dateline: string,
    lastpost: string,
    lastposter: string,
    views: number,
    replies: number,
    displayorder: string,
    heats: string,
    favtimes: string,
    maxposition: string
  },
  replyadd: boolean
}

export interface ISectionThreadListItem {
  tid: string,
  fid: string,
  author: string,
  authorid: string,
  subject: string,
  dateline: string,
  lastpost: string,
  lastposter: string,
  views: number,
  replies: string,
  displayorder: string,
  heats: string,
  favtimes: string,
  maxposition: string,
  typename: string,
  dbdateline: string,
  coverpath: string,
  content: string,
  forumname: string,
  hasAuth: boolean
}
